cloudStorage:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: comresourcesdocs
